AUJM1-53: Change spring framework to use java config from scanner
atl-mk/kotlin-p2 pull request #4
Opened 2022-10-24 02:33 UTC by jkim2-atlassian

Use java config instead of the spring scanner

2022-10-24 03:22 UTC, sinan-aumarah commented
We should also remove `atlassian-spring-scanner` from pom.xml

2022-10-24 03:23 UTC, sinan-aumarah requested changes

2022-10-24 03:23 UTC, sinan-aumarah commented on src/main/resources/META-INF/spring/plugin-context.xml
> +    <context:annotation-config/>
Make sure to remove atlassian-spring-scanner from pom.xml

2022-10-24 03:24 UTC, sinan-aumarah commented on src/main/resources/META-INF/spring/plugin-context.xml
> +    <context:annotation-config/>
Basically remove all of `<plugin>
                <groupId>com.atlassian.plugin</groupId>
                <artifactId>atlassian-spring-scanner-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>atlassian-spring-scanner</goal>
                        </goals>
                        <phase>process-classes</phase>
                    </execution>
                </executions>
                <configuration>
                    <verbose>false</verbose>
                </configuration>
            </plugin>`

2022-10-24 03:25 UTC, atl-mk commented
Oh, everything used to be Java config? meh, doesn't matter too much

2022-10-24 03:26 UTC, atl-mk commented on src/main/kotlin/com/atlassian/pedagogical/config/KotlinConfig.kt
> +    open fun exportFooService(foo: Foo): FactoryBean<ServiceRegistration<*>> =
exporting and importing should be in separate files respectively so that it's easier to manage

2022-10-26 02:22 UTC, jkim2-atlassian commented
> Please double check that the services are being exported and imported properly in the UPM OSGi page? We were having issues with this.

It's because plugin-context.xml was missing reference to the config class `<bean class="com.atlassian.pedagogical.config.KotlinConfig"/>
    <bean class="com.atlassian.pedagogical.config.JavaConfig"/>`

2022-10-26 04:17 UTC, sinan-aumarah approved these changes

2022-10-26 04:49 UTC, merged